FROM nginx:latest

# Create log files for nux game
ADD . /var/log/nginx/nux-game

RUN touch /var/log/nginx/nux-game/access.log
RUN touch /var/log/nginx/nux-game/error.log

# Create log files for nux game
ADD . /var/log/nginx/nux-game

RUN touch /var/log/nginx/nux-game/access.log
RUN touch /var/log/nginx/nux-game/error.log

EXPOSE 80
