FROM mysql

#RUN mkdir -p /docker-entrypoint-initdb.d
#ADD . /docker-entrypoint-initdb.d
#COPY scripts/1_init_db.sql /docker-entrypoint-initdb.d
#ADD ./scripts/1_init_db.sql /docker-entrypoint-initdb.d/
#ENTRYPOINT ["docker-entrypoint.sh"]

EXPOSE 3306
